### ISSUE TITLE
Override/ignore categories when sorting.

### ISSUE THREAD

**Issue by simontuffs** [Pogadog/anomalizer-ui#6]
It would be helpful to be able to turn off categories when sorting, but still display the surrounding highlight boxes.  For example, sort by Alphabetic should be able to sort globally A-Z, so that you can find metrics, irrespective of whether the metrics are hot/warm/cold.  Suggest use a checkbox to "sort by category", default checked, next to sort by dropdown (top right).

**Comment by philiptuffs** [comment]
Okay I'll implement this
